const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, reducedMotion: 'reduce' });
    const errors = []; page.on('pageerror', e => errors.push(e.message));
        await page.addInitScript(() => localStorage.setItem("telephony-panel-language", "pt-BR"));
    await page.goto('http://127.0.0.1:5169/?preview=true');
    const toggle = page.getByRole('checkbox', { name: 'Manter recursos já vistos', exact: true });
    await page.locator('.board-grid .board-tile').first().waitFor();
    assert(await toggle.isChecked(), 'Retention defaults on');
    assert.equal(await page.locator('.board-queues .board-tile').count(), 1);
    await page.getByRole('button', { name: 'Simular ausência de eventos', exact: true }).click();
    await page.waitForFunction(() => document.querySelectorAll('.board-tile.tone-busy,.board-tile.tone-online,.board-tile.tone-offline,.board-tile.tone-ringing').length === 0);
    assert.equal(await page.locator('.board-grid .board-tile').count(), 75, 'Known endpoints remain without events');
    assert.equal(await page.locator('.board-trunks .board-tile').count(), 1, 'Known trunk remains');
    assert.equal(await page.locator('.board-queues .board-tile').count(), 1, 'Queue remains');
    assert.equal(await page.locator('.tile-channel').count(), 0, 'No stale call details');
    const channelsOnly = page.getByRole('button', { name: 'Só com canais observados', exact: true });
    await channelsOnly.click();
    await page.waitForFunction(() => document.querySelectorAll('.board-tile').length === 0);
    assert(await toggle.isChecked(), 'Channel filter does not change retention');
    await channelsOnly.click();
    await page.waitForFunction(() => document.querySelectorAll('.board-grid .board-tile').length === 75);
    assert.equal(await page.locator('.board-trunks .board-tile').count(), 1);
    assert.equal(await page.locator('.board-queues .board-tile').count(), 1);
    await toggle.focus(); await toggle.press('Space');
    await page.waitForFunction(() => document.querySelectorAll('.board-tile').length === 0);
    await toggle.press('Space');
    await page.locator('.board-queues .board-tile').waitFor();
    const first = page.locator('.board-grid .board-tile').first();
    await first.focus(); await first.press('Enter');
    await page.getByText(/Última observação salva \(aproximada\)/).waitFor();
    assert.equal(await page.locator('.board-inspector .live-table').count(), 0);
    await page.getByRole('button', { name: 'Fechar detalhes', exact: true }).click();
    fs.mkdirSync('.impeccable/review', { recursive: true });
    await page.screenshot({ path: '.impeccable/review/inventory-desktop.png', fullPage: true });
    await page.getByRole('button', { name: 'Limpar recursos lembrados', exact: true }).click();
    await page.getByRole('button', { name: 'Cancelar limpeza', exact: true }).click();
    assert.equal(await page.locator('.board-grid .board-tile').count(), 75, 'Cancel does not clear');
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole('button', { name: 'Tema escuro', exact: true }).click();
    await page.getByRole('button', { name: 'Limpar recursos lembrados', exact: true }).click();
    await page.screenshot({ path: '.impeccable/review/inventory-mobile-confirm.png', fullPage: true });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'No mobile overflow');
    await page.getByRole('button', { name: 'Confirmar limpeza', exact: true }).click();
    await page.waitForFunction(() => document.querySelectorAll('.board-tile').length === 0);
    assert(await toggle.isChecked(), 'Clear does not disable retention');
    assert.equal(errors.length, 0, errors.join('\n'));
    console.log('PASS inventory UI: default on, peer/trunk/queue retention, no stale channels, toggle, keyboard, cancel/clear, desktop/mobile dark');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
