const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, reducedMotion: 'reduce' });
    const errors = []; page.on('pageerror', e => errors.push(e.message));
        await page.addInitScript(() => localStorage.setItem("telephony-panel-language", "pt-BR"));
    await page.goto('http://127.0.0.1:5169/?preview=true');
    await page.getByRole('button', { name: /^Configurar mesa/ }).click();
    await page.getByRole('button', { name: 'Nova regra', exact: true }).click();
    await page.getByRole('button', { name: 'Aplicar ao rascunho', exact: true }).click();
    await page.getByText('Informe um nome de até 80 caracteres para cada regra.', { exact: true }).waitFor();
    await page.getByRole('textbox', { name: 'Nome na mesa', exact: true }).fill('Operadora de teste');
    await page.getByRole('textbox', { name: 'Identificadores SIP/PJSIP', exact: true }).fill('PJSIP/6101\nPJSIP/6104');
    await page.getByRole('button', { name: 'Aplicar ao rascunho', exact: true }).click();
    await page.getByText('Regra aplicada ao rascunho. Confira a prévia e salve.', { exact: true }).waitFor();
    assert(await page.getByRole('button', { name: 'Salvar configuração', exact: true }).isEnabled());
    await page.getByRole('button', { name: /^Editar Operadora de teste$/ }).click();
    await page.getByRole('heading', { name: 'Editar regra', exact: true }).waitFor();
    fs.mkdirSync('.impeccable/review', { recursive: true });
    await page.screenshot({ path: '.impeccable/review/settings-desktop.png', fullPage: true });
    await page.getByRole('button', { name: 'Tema escuro', exact: true }).click();
    await page.getByRole('button', { name: 'Tema claro', exact: true }).waitFor();
    await page.screenshot({ path: '.impeccable/review/settings-dark.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: '.impeccable/review/settings-mobile.png', fullPage: true });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'No mobile page overflow');
    await page.getByRole('button', { name: 'Cancelar edição', exact: true }).click();
    await page.getByRole('button', { name: 'Salvar configuração', exact: true }).click();
    await page.getByText('Simulação salva somente nesta demonstração. Nenhum arquivo real foi alterado.', { exact: true }).waitFor();
    await page.getByRole('button', { name: /^Mesa de operação/ }).click();
    const trunk = page.locator('.board-trunks .board-tile').filter({ hasText: 'Operadora de teste' });
    await trunk.waitFor();
    assert.equal(await trunk.count(), 1, 'Aliases from same server grouped into one trunk');
    assert.equal(await page.locator('.board-grid .board-tile').count(), 73);
    await page.getByRole('button', { name: /^Configurar mesa/ }).click();
    await page.getByRole('checkbox', { name: 'Mostrar recursos sem regra correspondente' }).press('Space');
    await page.getByText('Recursos sem regra serão ocultados somente da mesa. Continuam nas demais abas.', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'Salvar configuração', exact: true }).click();
    await page.getByRole('button', { name: /^Mesa de operação/ }).click();
    await page.getByText('Nenhum ramal ou endpoint corresponde aos filtros.', { exact: true }).waitFor();
    assert.equal(await page.locator('.board-grid .board-tile').count(), 0);
    assert.equal(await page.locator('.board-trunks .board-tile').count(), 1);
    await page.getByRole('button', { name: /^Canais / }).click();
    await page.locator('.live-table tbody tr').first().waitFor();
    assert.equal(await page.locator('.live-table tbody tr').count(), 4, 'Presentation filters do not remove diagnostic channels');
    await page.getByRole('button', { name: /^Configurar mesa/ }).click();
    await page.getByRole('button', { name: 'Remover Operadora de teste', exact: true }).click();
    await page.getByRole('button', { name: 'Confirmar remoção', exact: true }).click();
    await page.getByRole('checkbox', { name: 'Mostrar recursos sem regra correspondente' }).press('Space');
    await page.getByRole('button', { name: 'Recarregar configuração', exact: true }).click();
    await page.getByRole('button', { name: 'Descartar e recarregar', exact: true }).click();
    await page.getByText('Configuração recarregada.', { exact: true }).waitFor();
    assert.equal(await page.locator('.settings-rule').count(), 1, 'Discard restores last saved configuration');
    assert.equal(errors.length, 0, errors.join('\n'));
    console.log('PASS settings: validation, draft, edit/cancel, save, alias grouping, hide unmatched, channel preservation, delete/discard, themes/mobile');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
