const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({ headless: true });
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
    const page = await context.newPage();
    const errors = []; page.on('pageerror', e => errors.push(e.message));
    const openFilters = async (target = page) => { if (!(await target.locator('#board-options').isVisible())) await target.locator('.board-filter-trigger').click(); };
    await page.goto('http://127.0.0.1:5169/mesa?preview=true&q=6101&text=peers');
    await page.waitForURL(/\/board\?/);
    await page.locator('.board-grid .board-tile').first().waitFor();
    assert.equal(await page.locator('html').getAttribute('lang'), 'en');
    await openFilters();
    assert.equal(await page.getByRole('textbox', { name: 'Filter resources', exact: true }).inputValue(), '6101');
    assert.equal(await page.locator('.board-grid .board-tile').count(), 1);
    assert.equal(await page.locator('.board-trunks .board-tile').count(), 1);
    await page.getByRole('button', { name: 'Clear filters', exact: true }).click();
    await page.waitForFunction(() => document.querySelectorAll('.board-grid .board-tile').length === 75);
    const picker = page.locator('#board-focus .language-picker');
    const language = async name => { await picker.getByRole('combobox').click(); await picker.getByRole('option', { name, exact: true }).click(); };
    await language('Português');
    await page.getByRole('textbox', { name: 'Filtrar recursos', exact: true }).waitFor();
    assert.equal(await page.evaluate(() => localStorage.getItem('telephony-panel-language')), 'pt-BR');
    await page.reload();
    await page.locator('.board-tile').first().waitFor(); await openFilters();
    await page.getByRole('textbox', { name: 'Filtrar recursos', exact: true }).waitFor();
    assert.equal(await page.locator('html').getAttribute('lang'), 'pt-BR');
    await language('English');
    await page.getByRole('textbox', { name: 'Filter resources', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Full screen', exact: true }).click();
    await page.waitForFunction(() => document.fullscreenElement?.id === 'board-focus');
    assert.equal(await page.evaluate(() => document.fullscreenElement.querySelectorAll('.panel-header,.live-tabs,.board-retention,.live-help,.observation-details').length), 0);
    assert.equal(await page.evaluate(() => document.fullscreenElement.querySelectorAll('.operator-board,.board-filter-header').length), 2);
    await openFilters();
    await page.getByRole('textbox', { name: 'Filter resources', exact: true }).fill('6101');
    await page.waitForURL(/q=6101/);
    await page.getByRole('button', { name: 'Clear filters', exact: true }).click();
    fs.mkdirSync('.impeccable/review', { recursive: true });
    await page.getByRole('button', { name: 'Close filters', exact: true }).click();
    await page.screenshot({ path: '.impeccable/review/board-focused-en.png' });
    await openFilters();
    await page.getByRole('button', { name: 'Exit full screen', exact: true }).click();
    await page.waitForFunction(() => !document.fullscreenElement);
    await openFilters();
    await page.getByRole('button', { name: 'Dark theme', exact: true }).click();
    await language('Português');
    await page.getByRole('button', { name: 'Tela cheia', exact: true }).click();
    await page.waitForFunction(() => document.fullscreenElement?.id === 'board-focus');
    if (await page.locator('#board-options').isVisible()) await page.getByRole('button', { name: 'Fechar filtros', exact: true }).click();
    await page.screenshot({ path: '.impeccable/review/board-focused-pt-dark.png' });
    await openFilters();
    await page.getByRole('button', { name: 'Sair da tela cheia', exact: true }).click();
    await page.waitForFunction(() => !document.fullscreenElement);
    const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, storageState: await context.storageState() });
    await mobile.goto(page.url());
    await mobile.locator('.board-tile').first().waitFor(); await openFilters(mobile);
    await mobile.getByRole('textbox', { name: 'Filtrar recursos', exact: true }).waitFor();
    await mobile.getByRole('button', { name: 'Fechar filtros', exact: true }).click();
    await mobile.screenshot({ path: '.impeccable/review/board-focused-mobile.png', fullPage: true });
    assert(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'No mobile overflow');
    const independent = await browser.newPage();
    await independent.goto('http://127.0.0.1:5169/board?preview=true');
    await independent.locator('.board-tile').first().waitFor(); await openFilters(independent);
    await independent.getByRole('textbox', { name: 'Filter resources', exact: true }).waitFor();
    assert.equal(await independent.locator('html').getAttribute('lang'), 'en', 'Language is not shared across sessions');
    assert.equal(errors.length, 0, errors.join('\n'));
    console.log('PASS English route, compatibility, language persistence/isolation, focused fullscreen and filters, responsive themes');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
