const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = []; page.on('pageerror', e => errors.push(e.message));
    await page.goto('http://127.0.0.1:5169/board?preview=true&tab=settings');
    await page.locator('.board-tile').first().waitFor();
    assert.equal(await page.locator('.panel-header,.live-tabs,.live-help,.board-legend,.board-retention,.board-focus-toolbar').count(), 0);
    assert((await page.locator('.board-section-heading').first().boundingBox()).y < 10);
    const menu = page.locator('#board-options');
    const trigger = page.locator('.board-filter-trigger');
    assert(!(await menu.isVisible()));
    await trigger.focus(); await trigger.press('Enter');
    await menu.waitFor();
    await page.getByRole('textbox', { name: 'Filter resources', exact: true }).fill('6101');
    await page.waitForURL(/q=6101/);
    const filteredUrl = page.url();
    await page.getByRole('button', { name: 'Close filters', exact: true }).click();
    assert(!(await menu.isVisible()));
    assert.equal(page.url(), filteredUrl);
    assert.equal(await page.locator('.board-grid .board-tile').count(), 1);
    await trigger.click(); await page.keyboard.press('Escape');
    assert(!(await menu.isVisible()));
    await page.reload(); await page.locator('.board-tile').first().waitFor();
    assert(!(await menu.isVisible()));
    assert.equal(await page.locator('.board-grid .board-tile').count(), 1);
    await trigger.click();
    assert.equal(await page.getByRole('textbox', { name: 'Filter resources', exact: true }).inputValue(), '6101');
    await page.getByRole('button', { name: 'Clear filters', exact: true }).click();
    await page.getByRole('combobox', { name: 'Observed server', exact: true }).click();
    await page.getByRole('option', { name: 'eveo-voip', exact: true }).click();
    assert(await menu.isVisible(), 'Nested SUI select preserves parent popover');
    await page.waitForURL(/node=eveo-voip/);
    await page.getByRole('button', { name: 'Full screen', exact: true }).click();
    await page.waitForFunction(() => document.fullscreenElement?.id === 'board-focus');
    if (await menu.isVisible()) await page.getByRole('button', { name: 'Close filters', exact: true }).click();
    await trigger.click();
    await page.getByRole('button', { name: 'Clear filters', exact: true }).click();
    await page.waitForFunction(() => document.querySelectorAll('.board-grid .board-tile').length === 75);
    await page.getByRole('button', { name: 'Close filters', exact: true }).click();
    assert((await page.locator('.board-grid').boundingBox()).height > 850, 'Board uses fullscreen height');
    await page.screenshot({ path: '.impeccable/review/board-only-desktop.png' });
    await trigger.click();
    await page.screenshot({ path: '.impeccable/review/board-only-filters.png' });
    await page.getByRole('button', { name: 'Exit full screen', exact: true }).click();
    await page.waitForFunction(() => !document.fullscreenElement);
    if (!(await menu.isVisible())) await trigger.click();
    const settings = page.getByRole('link', { name: 'Configure board', exact: true });
    const target = new URL(await settings.getAttribute('href'));
    assert.equal(target.pathname, '/'); assert.equal(target.searchParams.get('tab'), 'settings');
    const boardUrl = page.url();
    const opened = page.waitForEvent('popup');
    await page.getByRole('link', { name: 'Back to panel', exact: true }).click();
    const normal = await opened;
    await normal.locator('.panel-header').waitFor(); await normal.locator('.live-tabs').waitFor();
    assert.equal(await normal.locator('.board-legend').count(), 1, 'Normal page retains complete controls');
    assert.equal(page.url(), boardUrl, 'Normal page opens without replacing the dedicated tab');
    assert.deepEqual(errors, []);
    console.log('PASS board-only: no preamble, keyboard, nested menu, filter persistence, URL reload, fullscreen height, normal-page navigation');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
