// Synthetic Development fixture only. This test must not send telephone actions.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
    page.setDefaultTimeout(10000);
    const errors = [], actions = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('request', r => { if (r.url().includes('telephony/monitor/actions')) actions.push(r.url()); });
    await page.goto('http://127.0.0.1:5169/board?preview=true');
    await page.locator('.board-grid .board-tile').first().waitFor();
    const url = page.url();
    const geometry = () => page.evaluate(() => ({ y: scrollY, height: document.documentElement.scrollHeight,
      top: document.querySelector('.board-columns').getBoundingClientRect().top }));
    const initial = await geometry();
    const menu = page.getByRole('menu');
    const dialog = page.getByRole('dialog');
    fs.mkdirSync('.impeccable/review', { recursive: true });
    for (const section of ['.board-grid', '.board-trunks', '.board-queues']) {
      await page.locator(section + ' .board-tile').first().click({ button: 'right' });
      await menu.waitFor();
      assert.equal(await menu.getByRole('menuitem').count(), 5);
      if (section === '.board-grid') await page.screenshot({ path: '.impeccable/review/supervision-menu-desktop.png', fullPage: true });
      await page.keyboard.press('End');
      assert(await menu.getByRole('menuitem', { name: 'Whisper continuously by prefix', exact: true }).evaluate(el => el === document.activeElement));
      await menu.getByRole('menuitem', { name: 'Listen continuously by prefix', exact: true }).click();
      await dialog.waitFor();
      assert(await dialog.evaluate(el => el.matches(':modal')), 'Confirmation stays above dedicated board');
      const confirm = dialog.getByRole('button', { name: 'Confirm and call my extension', exact: true });
      await dialog.getByText('Demonstration: confirmation validated. No call was sent.', { exact: true }).waitFor();
      assert.equal(await dialog.getByRole('combobox').count(), 0, 'Unique prefix needs no selection');
      assert.equal(await confirm.count(), 0, 'Accepted confirmation cannot double submit');
      await page.keyboard.press('Escape'); await dialog.waitFor({ state: 'detached' });
      assert.equal(page.url(), url); assert.deepEqual(await geometry(), initial);
    }
    const active = page.locator('.board-grid .board-card').filter({ hasText: 'Hugo' }).first();
    await active.locator('.card-menu-trigger').click();
    await menu.getByRole('menuitem', { name: 'Whisper to a channel', exact: true }).click();
    assert.equal(await dialog.getByRole('combobox').count(), 0, 'Unique channel is preselected');
    await dialog.getByText('Whispering sends your voice to the selected channel, not automatically to an agent. Choose the agent leg, not the caller or trunk leg.', { exact: true }).waitFor();
    await page.screenshot({ path: '.impeccable/review/supervision-channel-desktop.png', fullPage: true });
    await dialog.getByRole('button', { name: 'Confirm and call my extension', exact: true }).click();
    await dialog.getByText('Demonstration: confirmation validated. No call was sent.', { exact: true }).waitFor();
    await page.keyboard.press('Escape'); await dialog.waitFor({ state: 'detached' });
    await active.locator('.card-menu-trigger').click();
    await menu.getByRole('menuitem', { name: 'Listen to a channel', exact: true }).click();
    await dialog.getByText('Demonstration: confirmation validated. No call was sent.', { exact: true }).waitFor();
    assert.equal(await dialog.getByRole('button', { name: 'Confirm and call my extension', exact: true }).count(), 0);
    await page.keyboard.press('Escape'); await dialog.waitFor({ state: 'detached' });
    await active.locator('.board-tile').focus();
    await page.keyboard.press('Shift+F10'); await menu.waitFor();
    await page.keyboard.press('Escape'); await menu.waitFor({ state: 'detached' });
    assert(await active.locator('.board-tile').evaluate(el => el === document.activeElement));
    await page.addInitScript(() => localStorage.setItem('telephony-panel-language', 'pt-BR'));
    await page.reload(); await page.locator('.board-tile').first().waitFor();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole('button', { name: 'Filtros e opções da mesa', exact: true }).click();
    const dark = page.getByRole('button', { name: 'Tema escuro', exact: true });
    if (await dark.count()) await dark.click();
    await page.getByRole('button', { name: 'Fechar filtros', exact: true }).click();
    await page.locator('.board-queues .card-menu-trigger').first().click();
    await menu.waitFor();
    const bounds = await menu.boundingBox();
    assert(bounds.x >= 0 && bounds.x + bounds.width <= 391, 'Menu remains within mobile viewport');
    await page.screenshot({ path: '.impeccable/review/supervision-menu-mobile.png', fullPage: true });
    await menu.getByRole('menuitem', { name: 'Ouvir continuamente por prefixo', exact: true }).click();
    await dialog.waitFor();
    await page.screenshot({ path: '.impeccable/review/supervision-prefix-mobile.png', fullPage: true });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'No horizontal page overflow');
    assert.equal(actions.length, 0, 'Demo cannot call live monitor API');
    await page.addInitScript(() => localStorage.setItem('telephony-panel-language', 'en'));
    await page.goto('http://127.0.0.1:5169/board?preview=true&supervisionpreview=multiple');
    await page.locator('.board-grid .board-card').filter({ hasText: 'Hugo' }).first().locator('.card-menu-trigger').click();
    await menu.getByRole('menuitem', { name: 'Listen to a channel', exact: true }).click();
    await dialog.getByRole('combobox', { name: 'Specific channel', exact: true }).waitFor();
    const multipleConfirm = dialog.getByRole('button', { name: 'Confirm and call my extension', exact: true });
    assert(await multipleConfirm.isDisabled(), 'Ambiguous channels do not auto-submit');
    await dialog.getByRole('combobox', { name: 'Specific channel', exact: true }).click();
    await page.getByRole('option').filter({ hasText: 'PJSIP/6007-000000ef' }).click();
    await multipleConfirm.click();
    await dialog.getByText('Demonstration: confirmation validated. No call was sent.', { exact: true }).waitFor();
    assert.equal(await multipleConfirm.count(), 0, 'Manual submission stays one-shot');
    assert.equal(actions.length, 0, 'Ambiguous demo cannot call live monitor API');
    await page.goto('http://127.0.0.1:5169/board?preview=true&supervisionpreview=idle&contextid=11111111-1111-7111-8111-111111111111');
    await page.locator('.board-grid .board-card').filter({ hasText: 'Hugo' }).first().locator('.card-menu-trigger').click();
    await menu.getByRole('menuitem', { name: 'Listen continuously by prefix', exact: true }).click();
    await dialog.getByText('Demonstration: confirmation validated. No call was sent.', { exact: true }).waitFor();
    assert.equal(await dialog.getByRole('combobox').count(), 0, 'Idle real endpoint resolver needs no manual mapping');
    assert.equal(await dialog.getByRole('button', { name: 'Confirm and call my extension', exact: true }).count(), 0);
    assert(await dialog.locator('code').filter({ hasText: 'PJSIP/6007-' }).count() === 1);
    await page.screenshot({ path: '.impeccable/review/supervision-idle-mobile.png', fullPage: true });
    assert.equal(actions.length, 0, 'Idle fixture never originates a real call');
    assert.deepEqual(errors, []);
    console.log('PASS board supervision: direct unique-prefix/channel listen, whisper confirmation, keyboard, overlays, duplicate guard, EN/PT, mobile/dark; no live calls');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
