const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
    const errors = []; page.on('pageerror', e => errors.push(e.message));
    const count = () => page.locator('.board-grid .board-tile').count();
        await page.addInitScript(() => localStorage.setItem("telephony-panel-language", "pt-BR"));
    await page.goto('http://127.0.0.1:5169/mesa?preview=true');
    await page.locator('.board-grid .board-tile').first().waitFor();
    assert.equal(await count(), 75);
    assert.equal(await page.locator('footer').count(), 0);
    assert.equal(await page.locator('.panel-navigation').count(), 0);
    assert.equal(await page.locator('.panel-header,.live-tabs,.board-retention,.board-legend,.board-focus-toolbar').count(), 0);
    assert((await page.locator('.board-section-heading').first().boundingBox()).y < 10, 'Board starts at the top');
    const openFilters = async () => { if (!(await page.locator('#board-options').isVisible())) await page.locator('.board-filter-trigger').click(); };
    await openFilters();
    const text = page.getByRole('textbox', { name: 'Filtrar recursos' });
    await text.fill('6101');
    await page.waitForURL(/q=6101/);
    await page.waitForFunction(() => document.querySelectorAll('.board-grid .board-tile').length === 1);
    assert.equal(await page.locator('.board-trunks .board-tile').count(), 0);
    await page.getByRole('checkbox', { name: 'Troncos', exact: true }).press('Space');
    await page.getByRole('checkbox', { name: 'Filas', exact: true }).press('Space');
    await page.waitForURL(url => url.searchParams.get('text') === 'peers');
    await page.waitForFunction(() => document.querySelectorAll('.board-queues .board-tile').length === 1);
    assert.equal(await page.locator('.board-trunks .board-tile').count(), 1, 'Unselected trunk category unaffected by text');
    assert.equal(await page.locator('.board-queues .board-tile').count(), 1, 'Unselected queues unaffected by text');
    const shared = page.url();
    await page.reload(); await page.locator('.board-grid .board-tile').first().waitFor();
    await openFilters();
    assert.equal(await text.inputValue(), '6101');
    assert.equal(await count(), 1);
    assert(!(await page.getByRole('checkbox', { name: 'Troncos', exact: true }).isChecked()));
    const other = await browser.newPage(); await other.goto(shared);
    await other.locator('.board-grid .board-tile').first().waitFor();
    assert.equal(await other.locator('.board-grid .board-tile').count(), 1, 'Shared link restores filters'); await other.close();
    await page.getByRole('checkbox', { name: 'Troncos', exact: true }).locator('xpath=ancestor::label').click();
    await page.waitForURL(url => url.searchParams.get('text') === 'peers,trunks');
    await page.goBack();
    await page.waitForURL(/text=peers(?:&|$)/);
    await page.waitForFunction(() => document.querySelectorAll('.board-trunks .board-tile').length === 1);
    await page.getByRole('button', { name: 'Limpar filtros', exact: true }).click();
    await page.waitForFunction(() => document.querySelectorAll('.board-grid .board-tile').length === 75);
    assert(!new URL(page.url()).searchParams.has('q'));
    fs.mkdirSync('.impeccable/review', { recursive: true });
    await page.screenshot({ path: '.impeccable/review/board-page-desktop.png', fullPage: true });
    await page.getByRole('button', { name: 'Fechar filtros', exact: true }).click();
    assert(!(await page.locator('#board-options').isVisible()));
    assert.equal(await count(), 75);
    await openFilters();
    await page.getByRole('button', { name: 'Só com canais observados', exact: true }).click();
    await page.waitForURL(/channels=true/);
    await page.getByRole('button', { name: 'Tema escuro', exact: true }).click();
    await page.screenshot({ path: '.impeccable/review/board-page-dark.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: '.impeccable/review/board-page-mobile.png', fullPage: true });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'No mobile overflow');
    assert.equal(errors.length, 0, errors.join('\n'));
    console.log('PASS dedicated board: scoped text, defaults, URL, reload/share/back, reset, desktop/dark/mobile');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
