const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
    const browser = await chromium.launch({ headless: true });
    try {
        const page = await browser.newPage({ viewport: { width: 1977, height: 1043 }, reducedMotion: 'reduce' });
        const errors = [];
        page.on('pageerror', e => errors.push(e.message));
        await page.addInitScript(() => localStorage.setItem("telephony-panel-language", "pt-BR"));
        await page.goto('http://127.0.0.1:5169/?preview=true');
        await page.locator('.board-grid .board-tile').first().waitFor();
        assert.equal(await page.locator('.board-grid .board-tile').count(), 75);
        assert.equal(await page.locator('.board-trunks .board-tile').count(), 1);
        assert.equal(await page.locator('#board-active').count(), 0, 'No duplicate channel section');
        const channelsOnly = page.getByRole('button', { name: 'Só com canais observados', exact: true });
        assert.equal(await channelsOnly.getAttribute('aria-pressed'), 'false', 'All resources shown by default');
        await channelsOnly.focus(); await channelsOnly.press('Space');
        await page.waitForFunction(() => document.querySelectorAll('.board-grid .board-tile').length === 1);
        assert.equal(await channelsOnly.getAttribute('aria-pressed'), 'true');
        assert.equal(await page.locator('.board-trunks .board-tile').count(), 0);
        assert.equal(await page.locator('.board-queues .board-tile').count(), 1, 'Waiting queue callers remain visible with the observed-channel filter');
        await page.getByRole('textbox', { name: 'Filtrar recursos' }).fill('6101');
        await page.waitForFunction(() => document.querySelectorAll('.board-tile').length === 0);
        await page.getByRole('textbox', { name: 'Filtrar recursos' }).fill('');
        await page.waitForFunction(() => document.querySelectorAll('.board-grid .board-tile').length === 1);
        await page.getByRole('button', { name: /^Canais / }).click();
        await page.locator('.live-table tbody tr').first().waitFor();
        assert.equal(await page.locator('.live-table tbody tr').count(), 4, 'Board filter does not hide diagnostic channels');
        await page.getByRole('button', { name: /^Mesa de operação/ }).click();
        assert.equal(await channelsOnly.getAttribute('aria-pressed'), 'true', 'Filter survives tab switch');
        await channelsOnly.click();
        await page.waitForFunction(() => document.querySelectorAll('.board-grid .board-tile').length === 75);
        assert.equal(await page.locator('.board-trunks .board-tile').count(), 1);
        assert.equal(await page.locator('.board-queues .board-tile').count(), 1);
        assert.equal(await page.locator('.board-grid .board-tile').filter({ hasText: 'Local/' }).count(), 0, 'Technical channels are not extension tiles');
        await page.getByRole('button', { name: /^Ramais e endpoints/ }).click();
        assert.equal(await page.locator('.resource').filter({ hasText: 'Local/' }).count(), 0, 'Manager endpoint tab also excludes Local cards');
        await page.getByRole('button', { name: /^Canais / }).click();
        await page.locator('.live-table tbody tr').first().waitFor();
        assert.equal(await page.locator('.live-table tbody tr').filter({ hasText: 'Local/' }).count(), 2, 'Both internal channel legs remain diagnosable');
        await page.getByRole('button', { name: /^Mesa de operação/ }).click();
        fs.mkdirSync('.impeccable/review', { recursive: true });
        await page.screenshot({ path: '.impeccable/review/board-user-1977.png', fullPage: true });
        await page.setViewportSize({ width: 1440, height: 1100 });
        await page.screenshot({ path: '.impeccable/review/board-desktop.png', fullPage: true });
        const first = page.locator('.board-grid .board-tile').first();
        await first.focus(); await page.keyboard.press('Enter');
        await page.locator('.board-inspector').waitFor();
        assert(await page.locator('.board-inspector').evaluate(el => document.activeElement === el));
        await page.getByRole('button', { name: 'Fechar detalhes', exact: true }).click();
        const filter = page.getByRole('textbox', { name: 'Filtrar recursos' });
        await filter.fill('6101');
        await page.waitForFunction(() => document.querySelectorAll('.board-grid .board-tile').length === 1);
        await filter.fill('missing-endpoint');
        await page.getByText('Nenhum ramal ou endpoint corresponde aos filtros.', { exact: true }).waitFor();
        await filter.fill('');
        await page.waitForFunction(() => document.querySelectorAll('.board-grid .board-tile').length === 75);
        await page.getByRole('button', { name: 'Tema escuro', exact: true }).click();
        await page.getByRole('button', { name: 'Tema claro', exact: true }).waitFor();
        await page.screenshot({ path: '.impeccable/review/board-dark.png', fullPage: true });
        await page.setViewportSize({ width: 390, height: 844 });
        await page.screenshot({ path: '.impeccable/review/board-mobile.png', fullPage: true });
        assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'No mobile page overflow');
        assert.equal(errors.length, 0, errors.join('\n'));
        await channelsOnly.click();
        await page.waitForFunction(() => document.querySelectorAll('.board-grid .board-tile').length === 1);
        await page.screenshot({ path: '.impeccable/review/board-mobile-filter.png', fullPage: true });
        assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'No mobile filter overflow');
        console.log('PASS operator board: channel toggle, no duplicate rail, diagnostic isolation, keyboard, composed filters, desktop/dark/mobile');
    } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
