[Service]
Environment=Panel__AcdSources__1__Node=eveo-voip
Environment=Panel__AcdSources__1__NodeId=01a08214-1954-72d0-80a2-7ae74b93951a
Environment=Panel__AcdSources__1__ContextIds__0=d21cfb04-9d37-473b-837c-67591a26feed
Environment=Panel__AcdSources__1__BaseUrl=http://172.19.2.104:18189/
Environment=Panel__AcdSources__1__KeyFile=/etc/sufficit/telephony-panel/acd-eveo-monitor.key
Environment=Panel__AcdSources__2__Node=apoint-voip
Environment=Panel__AcdSources__2__NodeId=01a08211-fa2b-7089-8cab-402b6a87d0d4
Environment=Panel__AcdSources__2__ContextIds__0=d21cfb04-9d37-473b-837c-67591a26feed
Environment=Panel__AcdSources__2__BaseUrl=http://172.19.1.104:18189/
Environment=Panel__AcdSources__2__KeyFile=/etc/sufficit/telephony-panel/acd-apoint-monitor.key
