<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Configurations>Debug;Release;Local</Configurations>
  </PropertyGroup>
	
	<ItemGroup Label="Sufficit Pack Items">
		<None Include="../icon.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
		<None Include="../license">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
		<None Include="../readme.md">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>
	
	<ItemGroup Label="Sufficit IA Configurations">
		<None Include="../.github/copilot-instructions.md">
			<Pack>False</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>
	
	<ItemGroup>
	  <Compile Remove="EventsPanelCardGroupedCollection.cs" />
	  <Compile Remove="EventsPanelReadOnlyCardMonitor.cs" />
	</ItemGroup>
	
	<!-- #region Sufficit Versioning Options V:202508251150 -->

	<PropertyGroup Label="Sufficit Versioning Options" Condition=" '$(TargetFramework)' == 'net9.0' ">
		<PkgVersion>[9.*,10.0.0)</PkgVersion>
		<LangVersion>12.0</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<!-- #endregion -->
	
	<ItemGroup>
		<PackageReference Include="Grpc.AspNetCore" Version="2.50.0" />
		<PackageReference Include="Grpc.AspNetCore.Server" Version="2.50.0" />
		<PackageReference Include="Grpc.AspNetCore.Web" Version="2.50.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="$(PkgVersion)" />
		<PackageReference Include="Microsoft.AspNetCore.Authorization" Version="$(PkgVersion)" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="$(PkgVersion)" />
		<PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
		<PackageReference Include="Microsoft.JSInterop" Version="$(PkgVersion)" />
	</ItemGroup>
	
	<ItemGroup Label="Sufficit Dependencies">
		<ProjectReference Include="..\..\sufficit-client\src\Sufficit.Client.csproj" Condition="Exists('..\\..\\sufficit-client\\src\\Sufficit.Client.csproj')" />
		<PackageReference Include="Sufficit.Client" Version="1.*" Condition="!Exists('..\\..\\sufficit-client\\src\\Sufficit.Client.csproj') " />

		<ProjectReference Include="..\..\sufficit-telephony-eventspanel\src\Sufficit.Telephony.EventsPanel.csproj" Condition="Exists('..\\..\\sufficit-telephony-eventspanel\\src\\Sufficit.Telephony.EventsPanel.csproj')" />
		<PackageReference Include="Sufficit.Telephony.EventsPanel" Version="1.*" Condition="!Exists('..\\..\\sufficit-telephony-eventspanel\\src\\Sufficit.Telephony.EventsPanel.csproj') " />

		<ProjectReference Include="..\..\sufficit-telephony-eventspanel-components\src\Sufficit.Telephony.EventsPanel.Components.csproj" Condition="Exists('..\\..\\sufficit-telephony-eventspanel-components\\src\\Sufficit.Telephony.EventsPanel.Components.csproj')" />
		<PackageReference Include="Sufficit.Telephony.EventsPanel.Components" Version="1.*" Condition="!Exists('..\\..\\sufficit-telephony-eventspanel-components\\src\\Sufficit.Telephony.EventsPanel.Components.csproj') " />

		<ProjectReference Include="..\..\sufficit-telephony-eventspanel-core\src\Sufficit.Telephony.EventsPanel.Core.csproj" Condition="Exists('..\\..\\sufficit-telephony-eventspanel-core\\src\\Sufficit.Telephony.EventsPanel.Core.csproj')" />
		<PackageReference Include="Sufficit.Telephony.EventsPanel.Core" Version="1.*" Condition="!Exists('..\\..\\sufficit-telephony-eventspanel-core\\src\\Sufficit.Telephony.EventsPanel.Core.csproj') " />
	</ItemGroup>	

</Project>
